version: '3.8'

services:
    
    web:
        build:
            context: .
            dockerfile: DockerFile
            extra_hosts:
              - "host.docker.internal:host-gateway"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - pgadmin
        environment:
            DATABASE_URL_VALUE: 'postgresql+psycopg2://brilla:password@db:5432/brillai'
            DOMAIN_NAME: http://localhost:3000
            ML_API_URL: https://humorous-polecat-liked.ngrok-free.app
  
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: brilla
            POSTGRES_PASSWORD: password
            POSTGRES_DB: brillai
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: brilla-ai@gmail.com
          PGADMIN_DEFAULT_PASSWORD: password@brilla
        ports:
          - "5050:80"
        depends_on:
          - db  

volumes:
    postgres_data: 



